# Content of the DMP

## Data Description
### Type of Data Being Collected
I will be collecting information regarding the concentration of a variety of oxylipins. I will also need to keep track
of the various samples being analyzed, and any relevant metadata pertaining to the analysis (such as
instrument/method parameters, system temperature, flow rates, etc). While the samples are from
humans, our lab is not facilitating the collection of the samples and all human samples will have been
de-identified prior to analysis. The raw data output will be in the form of graphs and/or datasheets.
One set of output data will be generated for each sample (the exact number of samples being analyzed is currently unknown).

For each sample, the following data will be collected:
* Data output graphs (2)
* Metadata from analysis (temperature, instrument parameters)
* Sample metadata (identifier, volume, concentration, preparation date)

## Roles and Responsibilities
In the research project, I will primarily perform data collection and analysis responsibilities, 
including data and metadata generation, data analysis, and data organization. The PI will be 
responsible for the management procedures, including protection of sensitive data (when 
applicable), data preservation, access control, and enforcement of the DMP. The Research 
Associate has traditionally been the main contact for instrument maintenance, quality control and 
software development/maintenance. I plan on continuing to rely on them for the maintenance and 
quality control aspects of the project. While I do not anticipate anyone leaving the research 
group, in the event that someone does leave, the PI will determine who will take on the 
responsibilities

## Storage and Security
### Data Storage
The data I will be handling as part of this research project is not considered sensitive or 
confidential according to OSU’s definitions. All samples will have been de-identified prior to 
being received by the lab. As far as I am aware, the data being collected will not need to be 
protected.

During the project, the raw data will be stored locally on the computer in the lab that is 
attached to the mass spectrometry system. Additional copies of raw and processed data will be 
kept in my Google Drive and OneDrive, and the PI will also retain a copy of all processed data.
Any physical data will be kept in a folder with my lab notebook to prevent loss or damage of the 
prints. If ever applicable, sensitive data or other data that needs to be protected will be stored in 
Box. In total, a minimum of 4 copies of processed data will be stored among different computers 
and operating systems to ensure that, in the event of a software failure, the data will not be lost. 
    
### Contingency Plan
To ensure that any data associated with my ONID account (including Google Drive and 
OneDrive) will not be lost upon my graduation, I will make sure the PI has a copy of all raw and 
processed data that was once stored on my account. My lab notebook and any physical printed 
data will also remain in the lab

# Data Standards and Metadata
### In order to maintain organization of documented data, a number of strategies will be utilized. 
Most importantly, virtual files will be carefully named with proper date and pertinent 
methodology information in the title of the document. These documents will then be placed in 
files that have been labeled for each sample. For example, a spectrograph generated by using a 
specific method would be labeled “YYYYMMDD-Method/InstrumentX-SampleX-TrialX”. This 
management method is applicable to written files and any generated graphs. Raw data output and 
instrumental metadata will be managed following the Mass Spectrometry Markup Language 
(mzML). This is further described in the next paragraph. In addition to this, all metadata will be 
organized as outlined in the Core Scientific Metadata Model (CSMD). This includes any code, 
method parameters, and sample documentation. Lastly, first-hand observations will be organized 
in a laboratory notebook and documented as outlined by the Open Geospatial Consortium’s
Standard for Observations and Measurements. All metadata and observations will be documented 
as soon as possible once the project has began, and any updates will be made when needed.

The Mass Spectrometry Markup Language (mzML) is a data standard that is specifically 
designed to document the complex raw data output of mass spectrometers.1 This data standard is 
based in XML and also supports the storage of metadata. An example mzML file is shown on the 
next page. Without getting deep into the specifics of lipidomic research, the mzML files contain
file metadata, spectrum metadata, scan data, and raw m/z data for the analysis. This data file 
contains all pertinent information for a single mass spectrometry sample run, and simplifies the 
sharing, distribution and analysis of this information.

# Access and Data Sharing
### There are no factors that will limit or delay the sharing of the data. Restricted data,
when applicable, may be shared to other members of the research team, as well as anyone
outside of the team who has received permission from the PI to receive the restricted data.
Data will be made publicly available upon publication of the first research paper to use the 
data. Data will be published as plain text files (.csv) on the National Metabolomics Data 
Repository. Data will fall under a CC-BY licensure to allow open access to the information with 
proper citing and attributions to the original work. Metadata will be shared similarly with the 
produced data and will fall under the same terms of use. In addition to this, laboratory notes 
will be kept by the PI and subsequently transferred to another faculty member or archived by 
the university.

# Archiving
### All data and metadata will be preserved via publication to the National Metabolomics 
Data Repository. This repository has been archiving metabolomics data sets since 2013, with 
the most recent archive being uploaded on May 19th, 2023. Although there is no specific 
archival time listed on the site, previous upload suggests a minimal preservation period of 10 
years if not longer. Accessed to the data will be maintained by the repository, which is 
sponsored by the Common Fund of the National Institute of Health. Upon deposition to the 
repository, uploaded files cannot be altered or removed unless formally done through the 
repository.

As stated above, all plain text files (.csv) and metadata files will be uploaded to the 
repository. Laboratory notebooks and analysis charts generated by the equipment will be 
retained by the research team and archived locally within the lab and/or university. Raw 
analysis charts (including LC/MS chromatograms and spectrographs) will be available upon 
request.
